default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: heroku-ready-rails-bootstrap_development

test:
  <<: *default
  database: heroku-ready-rails-bootstrap_test

production:
  <<: *default
  database: heroku-ready-rails-bootstrap_production
  username: heroku-ready-rails-bootstrap
  password: <%= ENV['HEROKU-READY-RAILS-BOOTSTRAP_DATABASE_PASSWORD'] %>
